name: 'cis_4400_project'  # Update this to reflect your project name
version: '1.0.0'
config-version: 2

# Profile for authentication and connection
profile: 'default'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Target path for compiled SQL files
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configure models
models:
  cis_4400_project:
    +persist_docs:
      description: false
      columns: false
    +materialized: table  # Default materialization for all models

    # Explicit folder-level overrides for cleaning
    cleaning:  
      +materialized: table

    # Explicit aliasing for specific models
    cleaned_311_noise_complaints:
      +alias: "311_Noise_Complaints_Cleaned"
      +materialized: table
    
    cleaned_dob_stalled_construction_sites:
      +alias: "DOB_Stalled_Construction_Cleaned"
      +materialized: table

    # Dimension tables
    Location_Dimension:  # Location dimension table
      +alias: "location_dim"
      +materialized: table
      
    Date_Dimension:  # Date dimension table
      +alias: "date_dim"
      +materialized: table
      
    Complaint_Type_Dimension:  # Complaint type dimension table
      +alias: "complaint_type_dim"
      +materialized: table

    # Fact table
    Integrated_Complaint_Fact_Table:  # Integrated fact table combining the two datasets
      +alias: "integrated_complaint_fact"
      +materialized: table
